using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aenor.MigracionTerceros.Clases
{
    public class NombreCamposTercero
    {
        #region CRM
        public static string Aen_AcronimoCRM = "aen_acronimo";
        public static string Aen_AlumnoCRM = "aen_alumno";
        public static string Aen_ProfesorCRM = "aen_profesor";
        public static string Aen_ResponsableCRM = "aen_responsable";
        public static string Aen_ApellidosCRM = "aen_apellidos";
        public static string Aen_ContactofacturacionidCRM = "aen_contactofacturacionid";
        public static string PrimarycontactidCRM = "primarycontactid";
        public static string Emailaddress1CRM = "emailaddress1";
        public static string ParentaccountidCRM = "parentaccountid";
        public static string Aen_DelegacionidCRM = "aen_delegacionid";
        public static string Aen_DepartamentoidCRM = "aen_departamentoid";
        public static string Aen_PaisdocumentoidCRM = "aen_paisdocumentoid";
        public static string TransactioncurrencyidCRM = "transactioncurrencyid";
        public static string Aen_EscertificaciondeproductosCRM = "aen_escertificaciondeproductos";
        public static string Aen_EscertificaciondesistemasCRM = "aen_escertificaciondesistemas";
        public static string Aen_EscertificadopequeocomercioCRM = "aen_escertificadopequeocomercio";
        public static string Aen_EsclienteCRM = "aen_escliente";
        public static string Aen_EsclientecertoolCRM = "aen_esclientecertool";
        public static string Aen_EsclientelaboratorioCRM = "aen_esclientelaboratorio";
        public static string Aen_EsclientewebCRM = "aen_esclienteweb";
        public static string Aen_EscompradordenormasCRM = "aen_escompradordenormas";
        public static string Aen_EsempleadoCRM = "aen_esempleado";
        public static string Aen_EslibreriaCRM = "aen_eslibreria";
        public static string Aen_EsmiembroctcCRM = "aen_esmiembroctc";
        public static string Aen_EsmiembrouneCRM = "aen_esmiembroune";
        public static string Aen_EsorganismoCRM = "aen_esorganismo";
        public static string Aen_EspotencialclientewebCRM = "aen_espotencialclienteweb";
        public static string Aen_EsclienteweberratumCRM = "aen_esclienteweberratum";
        public static string Aen_EsproveedorCRM = "aen_esproveedor";
        public static string Aen_EssuscriptorCRM = "aen_essuscriptor";
        public static string Aen_RevistaaenorCRM = "aen_revistaaenor";
        public static string StatecodeCRM  = "statecode";
        public static string Aen_EstadoclienteerpCRM = "aen_estadoclienteerp";
        public static string Aen_EstadoempleadoerpCRM = "aen_estadoempleadoerp";
        public static string Aen_EstadoproveedorerpCRM = "aen_estadoproveedorerp";
        public static string Aen_EstadosolicitudclienteerpCRM = "aen_estadosolicitudclienteerp";
        public static string Aen_EstadosolicitudempleadoerpCRM = "aen_estadosolicitudempleadoerp";
        public static string Aen_EstadosolicitudproveedorerpCRM = "aen_estadosolicitudproveedorerp";
        public static string Aen_FacturacionaenorCRM = "aen_facturacionaenor";
        public static string Aen_Facturacionaenor_BaseCRM = "aen_facturacionaenor_base";
        public static string FaxCRM = "fax";
        public static string Aen_FechadealtaCRM = "aen_fechadealta";
        public static string Aen_FechadebajaCRM = "aen_fechadebaja";
        public static string Aen_IdentificadorterceroCRM = "aen_identificadortercero";
        public static string Aen_claveintegracionCRM = "aen_claveintegracion";
        public static string Aen_ClienteerpidCRM = "aen_clienteerpid";
        public static string Aen_EmpleadoerpidCRM = "aen_empleadoerpid";
        public static string Aen_ProveedorerpidCRM = "aen_proveedorerpid";
        public static string Aen_IndustriaaenorCRM = "aen_industriaaenor";
        public static string RevenueCRM = "revenue";
        public static string Revenue_BaseCRM = "revenue_base";
        public static string Aen_loginempleadoCRM = "aen_loginempleado";
        public static string Aen_NombredelclienteCRM = "aen_nombredelcliente";
        public static string NameCRM = "name";
        public static string Aen_NumerodocumentoCRM = "aen_numerodocumento";
        public static string Aen_ObservacionesCRM = "aen_observaciones";
        public static string Aen_OrigenCRM = "aen_origen";
        public static string Aen_RiesgopagoaxesorCRM = "aen_riesgopagoaxesor";
        public static string Aen_SectoraenorCRM = "aen_sectoraenor";
        public static string Aen_GeneroCRM = "aen_genero";
        public static string Aen_SiglasCRM = "aen_siglas";
        public static string WebsiteurlCRM = "websiteurl";
        public static string Aen_SubtipodeterceroCRM = "aen_subtipodetercero";
        public static string Telephone1CRM = "telephone1";
        public static string Aen_TipodocumentoCRM = "aen_tipodocumento";
        public static string Aen_TipopersonaCRM = "aen_tipopersona";
        public static string Aen_TipoproveedorCRM = "aen_tipoproveedor";
        public static string Aen_ObservacionesmigracionCRM = "aen_observacionesmigracion";
        public static string NumberofemployeesCRM = "numberofemployees";
        #endregion CRM



        #region ORACLE
        public static string Aen_AcronimoORACLE = "aen_acronimo";
        public static string Aen_AlumnoORACLE = "aen_alumno";
        public static string Aen_ProfesorORACLE = "aen_profesor";
        public static string Aen_ResponsableORACLE = "aen_responsable";
        public static string Aen_ApellidosORACLE = "aen_apellidos";
        public static string Aen_ContactofacturacionidORACLE = "aen_contactofacturacionid";
        public static string PrimarycontactidORACLE = "primarycontactid";
        public static string Emailaddress1ORACLE = "emailaddress1";
        public static string ParentaccountidORACLE = "parentaccountid";
        public static string Aen_DelegacionidORACLE = "aen_codigodelegacion";
        public static string Aen_DepartamentoidORACLE = "aen_departamentoid";
        public static string Aen_PaisdocumentoidORACLE = "aen_paisdocumentoid";
        public static string TransactioncurrencyidORACLE = "transactioncurrencyid";
        public static string Aen_EscertificaciondeproductosORACLE = "aen_escertificaciondeprod";
        public static string Aen_EscertificaciondesistemasORACLE = "aen_escertificaciondesist";
        public static string Aen_EscertificadopequeocomercioORACLE = "aen_escertificadopc";
        public static string Aen_EsclienteORACLE = "aen_escliente";
        public static string Aen_EsclientecertoolORACLE = "aen_esclientecertool";
        public static string Aen_EsclientelaboratorioORACLE = "aen_esclientelaboratorio";
        public static string Aen_EsclientewebORACLE = "aen_esclienteweb";
        public static string Aen_EscompradordenormasORACLE = "aen_escompradordenormas";
        public static string Aen_EsempleadoORACLE = "aen_esempleado";
        public static string Aen_EslibreriaORACLE = "aen_eslibreria";
        public static string Aen_EsmiembroctcORACLE = "aen_esmiembroctc";
        public static string Aen_EsmiembrouneORACLE = "aen_esmiembroune";
        public static string Aen_EsorganismoORACLE = "aen_esorganismo";
        public static string Aen_EspotencialclientewebORACLE = "aen_espotencialclienteweb";
        public static string Aen_EsclienteweberratumORACLE = "aen_esclienteweberratum";
        public static string Aen_EsproveedorORACLE = "aen_esproveedor";
        public static string Aen_EssuscriptorORACLE = "aen_essuscriptor";
        public static string Aen_RevistaaenorORACLE = "aen_revistaaenor";
        public static string StatecodeORACLE  = "statecode";
        public static string Aen_EstadoclienteerpORACLE = "aen_estadoclienteerp";
        public static string Aen_EstadoempleadoerpORACLE = "aen_estadoempleadoerp";
        public static string Aen_EstadoproveedorerpORACLE = "aen_estadoproveedorerp";
        public static string Aen_EstadosolicitudclienteerpORACLE = "aen_estadosolclierp";
        public static string Aen_EstadosolicitudempleadoerpORACLE = "aen_estadosolempleadoerp";
        public static string Aen_EstadosolicitudproveedorerpORACLE = "aen_estadosolproveeerp";
        public static string Aen_FacturacionaenorORACLE = "aen_facturacionaenor";
        public static string FaxORACLE = "fax";
        public static string Aen_FechadealtaORACLE = "aen_fechadealta";
        public static string Aen_FechadebajaORACLE = "aen_fechadebaja";
        public static string Aen_IdentificadorterceroORACLE = "aen_identificadortercero";
        public static string Aen_claveintegracionORACLE = "aen_claveintegracion";
        public static string Aen_ClienteerpidORACLE = "aen_clienteerpid";
        public static string Aen_EmpleadoerpidORACLE = "aen_empleadoerpid";
        public static string Aen_ProveedorerpidORACLE = "aen_proveedorerpid";
        public static string Aen_IndustriaaenorORACLE = "aen_industriaaenor";
        public static string RevenueORACLE = "revenue";
        public static string Revenue_BaseORACLE = "revenue_base";
        public static string Aen_loginempleadoORACLE = "aen_loginempleado";
        public static string Aen_NombredelclienteORACLE = "aen_nombredelcliente";
        public static string NameORACLE = "name";
        public static string Aen_NumerodocumentoORACLE = "aen_numerodocumento";
        public static string Aen_ObservacionesORACLE = "aen_observaciones";
        public static string Aen_OrigenORACLE = "aen_origen";
        public static string Aen_RiesgopagoaxesorORACLE = "aen_riesgopagoaxesor";
        public static string Aen_SectoraenorORACLE = "aen_sectoraenor";
        public static string Aen_GeneroORACLE = "aen_genero";
        public static string Aen_SiglasORACLE = "aen_siglas";
        public static string WebsiteurlORACLE = "websiteurl";
        public static string Aen_SubtipodeterceroORACLE = "aen_subtipodetercero";
        public static string Telephone1ORACLE = "telephone1";
        public static string Aen_TipodocumentoORACLE = "aen_tipodocumento";
        public static string Aen_TipopersonaORACLE = "aen_tipopersona";
        public static string Aen_TipoproveedorORACLE = "aen_tipoproveedor";
        public static string Aen_ObservacionesmigracionORACLE = "aen_observacionesmigracion";
        public static string NumberofemployeesORACLE = "numberofemployees";
        #endregion ORACLE
    }
}
